require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc

MACHINE_FEATURES = "usbhost usbgadget alsa serial"

SERIAL_CONSOLES = "115200;ttyLP0"

PREFERRED_PROVIDER_virtual/kernel = "linux-rozalin"
PREFERRED_PROVIDER_trusted-firmware-a = "nxp-trusted-firmware-a"
PREFERRED_PROVIDER_optee-os = "nxp-optee-os"
PREFERRED_PROVIDER_optee-os-tadevkit = "nxp-optee-os-tadevkit"
PREFERRED_PROVIDER_optee-examples = "nxp-optee-examples"
KERNEL_DEVICETREE = "freescale/imx91-11x11-frdm-s.dtb"
KERNEL_IMAGETYPE = "Image"

SECO_FIRMWARE_NAME = "mx91a0-ahab-container.img"

PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-rozalin"
EXTRA_IMAGEDEPENDS += "virtual/bootloader"
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = "kernel-devicetree"
UBOOT_CONFIG ??= "nand"
UBOOT_CONFIG[nand] = "imx91s_11x11_frdm_defconfig"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " \
    kernel-module-dwmac-imx \
    kernel-module-imx7ulp-wdt \
    kernel-module-imx93-adc \
    kernel-module-nvmem-imx-ocotp-ele \
    kernel-module-nxp-bbnsm-pwrkey \
    kernel-module-qoriq-thermal \
    kernel-module-reset-gpio \
    kernel-module-rtc-nxp-bbnsm \
    kernel-module-rtc-pcf2127 \
    kernel-module-tcpci \
    kernel-module-nxp-wlan \
    firmware-nxp-wifi-nxpiw610-sdio \
    firmware-nxp-wifi-conf \
"

IMAGE_BOOT_FILES ?= " \
    ${KERNEL_IMAGETYPE} \
    ${@os.path.basename(d.getVar("KERNEL_DEVICETREE"))} \
"
MKUBIFS_ARGS = "-m 2048 -e 126976 -c 1536"
UBINIZE_ARGS = "-m 2048 -p 128KiB -s 2048"
IMAGE_FSTYPES:append = " ubifs squashfs"
EXTRA_IMAGEDEPENDS += "factory-provisioning-tools"
