interface=uap0
driver=nl80211
ssid=TestAP
hw_mode=g
channel=1
wmm_enabled=1
country_code=PL

ieee80211d=1
ieee80211n=1
ieee80211ac=1
ieee80211ax=1

wpa=2
wpa_pairwise=CCMP
wpa_passphrase=1234567890
wpa_key_mgmt=SAE
wpa_group_rekey=1800
rsn_pairwise=CCMP
ieee80211w=2
sae_groups=21
sae_require_mfp=1
sae_anti_clogging_threshold=10
